name: Build

on:
  push:
    branches:
      - main


env:
  working-directory: ./

jobs:
  Deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run integration tests
      run: pytest 
    - name: Run deployment
      if: success()
      run:  |
        prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }} 
        prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}
        python ./deployment.py
      working-directory: ${{env.working-directory}}

